### ISSUE TITLE
Try to code several webpages in Pre

### ISSUE THREAD

**Issue by dpashkevich** [jonschlinkert/pre#26]
Just take front pages of some popular sites and try to code them in Pre. Of course some bulk can be trimmed, what's important is to see how Pre suits as a shorthand to HTML in the real world.

**Comment by jonschlinkert** [comment]
Great idea, I'll start with bootstrap and HTML5 boilerplate, so we can demo sites coded using best practices, rather than trying to reverse engineer poorly coded sites or generated code.

**Comment by dpashkevich** [comment]
I'll try something too. It would be better to post the code in gists since it can be pretty long...

**Comment by jonschlinkert** [comment]
Agreed

Sent from my iPhone

**Comment by dpashkevich** [comment]
You know what, I started doing this by hand but got bored after having written about 10 lines... So I created this quick snippet that would traverse the DOM of current page and output Pre markup :)

Here it is: https://gist.github.com/4024183

You can save it to Chrome Developer Tools' `Snippets` but it's best executed directly from the console because that way you can have the output copied right to your clipboard... It's quick and dirty and incomplete but helps you quickly get an idea of _"how this webpage would be coded in Pre"_.

Notes:
- As said, the code is quick & dirty. It's not robust and has quirks
- Since it's a runtime script, it captures the current state of DOM, not initial HTML fetched from the web server
- Doctype isn't represented at all
- Colons `:` in attribute names are replaced for dashes `-` (e.g.  `xmlns:dc` would be converted to `xmlns-dc`)
- Quotes inside attribute values aren't escaped
- No escaping done for text or comment node contents
- Syntax for text nodes used: `text { hello i am text }`
- Syntax for comment nodes used: `comment { hello I am comment }`
- Empty nodes are put on one line for better readability, e.g. `p {}`
- One-line text nodes are kept on one line for better readability, e.g. `text { hello i am a line of text }`

Feel free to play around!

**Comment by jonschlinkert** [comment]
Wow! I can't wait to try this. I'm on a business trip until tomorrow evening, but I will probably be able to check it out sometime today. Thanks!

Sent from my iPhone

**Comment by doowb** [comment]
Holy crap!!! that's awesome. For starters... I didn't know there was the snippet function in Chrome.

I'll have to look at the code some more, but would it be difficult to reverse it?

**Comment by dpashkevich** [comment]
The snippet function landed recently but looks like it's gonna have a great potential. One thing that slightly disappoints me now is that currently the code isn't executed in console's context. This means you don't have stuff like `copy()`, `$0`, `$1`, `$_` when executing snippets. The only workaround so far is just copy-paste snippet code into the console...

> I'll have to look at the code some more, but would it be difficult to reverse it?

You mean generate HTML code from Pre code? Well it's a completely different thing, that would require a Pre parser :) Since Pre is heavily based on LESS, I'm planning on playing around with LESS' parser at least for the first implementation...

**Comment by jonschlinkert** [comment]
This is awesome! @dpashkevich good job. I'm impressed at how thorough it is

**Comment by dpashkevich** [comment]
In light of the election day, http://whitehouse.gov coded in Pre: https://gist.github.com/4031991

Some findings:
- An uncommon doctype used: `XHTML+RDFa 1.0`
- "Ugly" XML attributes:
  - xmlns:dc
  - xmlns:ctag
- Lots of Barrack's in meta keywords :)
- Trying to put inline `<style>`s in the document causes a disaster, total cognitive dissonance! This should probably be prohibited, would it be a serious limitation?
- IE conditional comments used. These definitely need a special syntax in Pre, you don't want this:

``` sass
comment {
[if lte IE 8]>
    <link type="text/css" rel="stylesheet" media="all" href="/sites/default/themes/framedynamic/css/ie.css" />
  <![endif]
    }
```

---
- Putting each attribute on new line significantly increases document length :)
  Perhaps sometimes you would want to put one-liners for inline elements, e.g.

``` sass
a {href: "/itgetsbetter"; text {It Gets Better}}
```

insead of

``` sass
a {
  href: "/itgetsbetter"; 
  text {It Gets Better}
}
```

But URLs can easily be pretty long, so I would leave the below as is:

``` sass
img {
  src: "/sites/default/files/taxes/nav_feature_taxes.jpg";
  alt: "Explore the President's Plan";
}
```

---
- I **love** the way form markup looks in Pre

``` sass
form#usasearch-box {
  action: "http://search.whitehouse.gov/search";
  accept-charset: "UTF-8";
  method: "get";

  div {
    input#edit-affiliate-id {
      type: "hidden";
      name: "affiliate";
      value: "wh";
    }
    #edit-text-field-wrapper.form-item {

      input#edit-text-field.form-text.search-field {
        type: "text";
        maxlength: "128";
        name: "query";
        size: "15";
        value: "";
        title: "Enter the terms you wish to search for.";
      }
    }
    input#edit-submit.form-submit.search-btn {
      type: "image";
      name: "submit";
      value: "Search";
      alt: "search";
      src: "/sites/default/themes/framedynamic/img/wh_home_search_icon.png";
    }
    input#edit-usasearch-box {
      type: "hidden";
      name: "form_id";
      value: "usasearch_box";
    }
  }
}
```

**Comment by jonschlinkert** [comment]
I love this, that snippet you created is a great way to keep exposing issues that need to be addressed. I just got back from my trip (after spending 20 hours in the SFO airport! lol), so I'll have more time to review later, but here are some initial thoughts:
- there are many uncommon html/xml attributes that follow this patttern: "xmlns:dc"   So maybe rather than creating keywords for these, we make a rule that addresses that pattern. Need to give it more thought, but that seems like the right direction.
- I think doctypes should still be keywords, but maybe we make them parametric somehow to avoid having to hard code too many. We can spend some time thinking about syntax.
- the style tag is something i've gone back and forth on. After I have a chance to go back and review what I've already written down on this I'll probably create another issue and link to it. I think that one deserves it's own issue :)
- I think coding style is something that will be left to the developer. I completely agree about your point about inline vs. block style and that sometimes one is more appropriate than the other. I good place to start with that is twitter RECESS. I think we should consider using recess instead of (or in addition to LESS), since it makes code so much more readable. We can set our own rules for ordering attributes, etc. but I like the idea of being opinionated at first. Sure, it will polarize opinions, but it will make pre much easier to learn.
- We can also filter out superfluous "barrack's" when those are encountered... jk :)
- IE conditional comments: we do need a syntax for that, and I think I have something in mind but I need to play around with it first. I'm still not sold 100% on why we shouldn't allow regular CSS style /\* block comments */ - which would be a good starting point here.  It's so much cleaner and obvious. In regards to where the comments show up, we can set some hard rules about how that works and adjust when we get feedback and more use cases.  
- I think we need to use includes as well.  I mentioned this somewhere else, but includes have a different advantage than mixins. If implemented wisely, I think includes should allow you to include and compile straight HTML right along with the rest of your pre code. So includes could help resolve some complicated edge cases, and also keep pre prettier and focused on resolving problems related to repetitious code and mainstream use cases.

**Comment by jonschlinkert** [comment]
I agree about how Pre looks with form markup... makes it very obvious where the opportunities for mixins, includes, and general refactoring are :)

**Comment by dpashkevich** [comment]
- Uncommon xml attributes - I previously suggested having a built-in system mixin that has some special logic under the hood. A user would write something like `attr("xmlns:dc", "http://purl.org/dc/terms")`, the parser recognizes a reserved keyword (`attr`) and instead of processing the directive like a regular mixin, it figures that it needs to place an attribute with a specified name in the output html.
- Agree on doctype keywords + generic way of specifying custom doctypes. The implementation can be the same as with custom attributes - a built-in mixin with a reserved name
- style tag - ok, I'm waiting for you to create an issue on this with your thoughts
- Good point about RECESS (though I've always felt too lazy to enforce manual ordering of properties/attributes). Also, RECESS ideas will be useful for Dry.
- Comment syntax - I'm still open about trying it the way you suggest
- Agree on includes. Of course that way we can include not only HTML but markdown/textile and any other kinds of documents. You linked to the way Jade implements this, I'm bringing it up here:
  https://github.com/visionmedia/jade#a13
  http://tjholowaychuk.com/post/7590787973/jade-mixins-includes

**Comment by jonschlinkert** [comment]
For uncommon attributes, what if we allowed: 

```
E[attr="value"] {}
```

This is how specific attributes are targeted in CSS, so probably worth considering. So this:

``` css
html[xml:lang="en"] {
  lang: "en";
  xmlns: "http://www.w3.org/1999/xhtml";
}
```

compiles to:

``` html
<html xml:lang="en" lang="en" xmlns="http://www.w3.org/1999/xhtml">
```

**Comment by dpashkevich** [comment]
Can be an option but we probably still need a way to specify them in the body, along with other attrs...
